vars:
  - params.yaml

stages:
  query:
    wdir: ../../
    cmd: >-
      python -m src.query_foursquare_bycc
      --countrycode ${countrycode}
      --filename ${filename}
    outs:
      - ./data/raw/${filename}.gpkg
  clean:
    wdir: ../../
    deps:
      - ./data/raw/${filename}.gpkg
    cmd: >-
      python -m src.clean_foursquare
      --filename ${filename}
    outs:
      - data/processed/${filename}.parquet
  korea_postprocessing:
    wdir: ../../
    deps:
      - ./data/processed/${filename}.parquet
    cmd: >-
      python -m src.korea_postprocessing
      --filename ${filename}
    outs:
      - ./data/processed/${filename}_open.parquet




