vars:
  - params.yaml

stages:
  query:
    wdir: ../../
    cmd: >-
      python -m src.query_foursquare
      ${bounds}
      --filename ${filename}
    outs:
      - ./data/raw/${filename}.gpkg
  clean:
    wdir: ../../
    deps:
      - ./data/raw/${filename}.gpkg
    cmd: >-
      python -m src.clean_foursquare
      --filename ${filename}
    outs:
      - data/processed/${filename}.parquet
  uk_postprocessing:
    wdir: ../../
    deps:
      - ./data/processed/${filename}.parquet
    cmd: >-
      python -m src.uk_postprocessing
      --filename ${filename}
    outs:
      - ./data/processed/${filename}_admin.parquet
